### ISSUE TITLE
[BUG] Failure to parse template.json

### ISSUE THREAD

**Issue by ilin-argirov** [Qballjos/portainer_templates#18]
**Describe the bug**
Following the listed instructions in the readme, I placed https://raw.githubusercontent.com/Qballjos/portainer_templates/master/Template/template.json as a template source in portainer. Upon going to the App Templates page, I get the following error:

![screenshot_230](https://user-images.githubusercontent.com/45467536/98407328-255dca00-2078-11eb-9f79-21a621d06716.png)

**Portainer Logs**
2020/11/06 19:34:48 http error: Unable to parse external templates (err=json: cannot unmarshal object into Go value of type []portainer.Template) (code=500)

**Comment by Qballjos** [comment]
Witch version of portainer are you using? The template you are trying to use is for portainer ce

**Comment by ilin-argirov** [comment]
Yes, I am using Portainer CE v1.24.1. Is there any way I can assist with fixing the template json?

**Comment by Qballjos** [comment]
I think you are missing something because portainer ce is version 2.0.0
![image](https://user-images.githubusercontent.com/1911646/98416958-63f78280-2080-11eb-9999-317148c0667e.png)

for you're version of portainer the template below should work:
https://raw.githubusercontent.com/Qballjos/portainer_templates/master/V1 Template/template.json

this is the old one that isn't being maintained anymore

**Comment by ilin-argirov** [comment]
Yep, you are right! I should have read the disclaimer in the portainer/portainer docker listing.
