### ISSUE TITLE
[APP REQUEST]: Raspberry pi variant

### ISSUE THREAD

**Issue by drhat** [Qballjos/portainer_templates#31]
Quite simply I would humbly request a variant of all this, compatible with a raspberry pi 4. Thank you for your work.

**Comment by Qballjos** [comment]
The issue is that not all images support arm (raspberry pi cpu) bassed hosts, there for this would be a huge task. 
I'm willing to have a look at creating a sepperate template if you could send me a list of wanted applications, keep in mind that a raspberry pi is just a small board and not that good at running heavy containers. I own al pi's till the 3b+ I havent had the need to buy a 4.
